name: qr_code_reader
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1
  supabase_flutter: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos.png
  fonts:
    - family: Clashdisplay
      fonts:
        - asset: assets/fonts/Clashdisplay-Regular.otf
          weight: 400
        - asset: assets/fonts/Clashdisplay-Light.otf
          weight: 300
        - asset: assets/fonts/Clashdisplay-Extralight.otf
          weight: 200
        - asset: assets/fonts/Clashdisplay-Medium.otf
          weight: 500
        - asset: assets/fonts/Clashdisplay-Semibold.otf
          weight: 600
        - asset: assets/fonts/Clashdisplay-Bold.otf
          weight: 700
